### PR TITLE
new items????

### PR DESCRIPTION
**Pull request by alanlichen**
fill in the placeholders for me plox

### CODE REVIEW

**Comment by alanlichen** [comment]
Wow sad merge conflicts

**Comment by Codemonkey51** [comment]
> Wow sad merge conflicts

F

**Comment by alanlichen** [comment]
IDK how to resolve these conflicts... Ima just wait for hithere to get on lol

**Comment by cursorweb** [comment]
ok i'll do it

**Comment by alanlichen** [comment]
THANKS THONKS THINGS THANKSSSS

**Comment by alanlichen** [comment]
Closing this pr because merge conflicts are very annoying & items were already added to the code.
image

**Pull request closed without merging**
