### PR TITLE
i honestly dont know what im doing

### PR DESCRIPTION
**Pull request by alanlichen**

### CODE REVIEW

**Comment by alanlichen** [comment]
Update price if its bad :/

**Comment by cursorweb** [comment]
how did you crack my state-of-the-art algorithm of determining prices?
`y=50(x+5)`

**Comment by alanlichen** [comment]
im not good at item names so uh yeah

**Comment by alanlichen** [comment]
> how did you crack my state-of-the-art algorithm of determining prices?
> `y=50(x+5)`

idk

**Pull request merged**
